services:
  db:
    image: postgres:15
    container_name: novel_pg
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DBNAME}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  spider:
    build: .
    container_name: novel_spider
    depends_on:
      - db
    environment:
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DBNAME: ${PG_DBNAME}
    volumes:
      - ./output:/app/output
    command: ["python", "run.py", "crawl", "auto_novel_top100_postgre"]